### ISSUE TITLE
template render fail

### ISSUE THREAD

**Issue by LeeFo-china** [wuyue92tree/django-adminlte-ui#1]
Invalid block tag on line 70: 'change_list_object_tools', expected 'endblock'. Did you forget to register or load this tag?
In template /home/leefo/www/lib/python3.6/site-packages/adminlteui/templates/admin/change_list.html, error at line 70

**Comment by wuyue92tree** [comment]
the {% change_list_object_tools %} is load from  templatetags  admin_list in django without a `block`, did you try to rewrite this page?

**Comment by wuyue92tree** [comment]
> Invalid block tag on line 70: 'change_list_object_tools', expected 'endblock'. Did you forget to register or load this tag?
> In template /home/leefo/www/lib/python3.6/site-packages/adminlteui/templates/admin/change_list.html, error at line 70

The {% change_list_object_tools %} is load from templatetags `admin_list` in django without `block`, did you try to rewrite this page?

Maybe this is better for you.
```
{% extends "admin/change_list.html" %}
{% load i18n %}
{% block object-tools-items %}

# new button
<button class="btn btn-danger">{% trans 'New Button' %}</button>
{{ block.super }}
{% endblock %}
```
