### ISSUE TITLE
点击菜单设置时，出现这个错误，'admin_tree' is not a registered tag library. Must be one of:

### ISSUE THREAD

**Issue by valuabledata** [wuyue92tree/django-adminlte-ui#13]
TemplateSyntaxError at /admin/django_admin_settings/menu/
'admin_tree' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
adminlte_list
adminlte_menu
adminlte_options
cache
i18n
l10n
log
static
staticfiles
tz

**Comment by TysonRV** [comment]
@valuabledata You probably have to add `treebeard` to the `INSTALLED_APPS` setting in your app. 

It is mentioned [here](https://django-adminlte-ui.readthedocs.io/en/latest/#setup)
