### ISSUE TITLE
太喜欢了，非常需要一个自定义功能模块的案例参考

### ISSUE THREAD

**Issue by KissWorld** [wuyue92tree/django-adminlte-ui#22]
太喜欢了，非常需要一个自定义功能模块的案例参考，比如视频列表啥的。

**Comment by wuyue92tree** [comment]
> 太喜欢了，非常需要一个自定义功能模块的案例参考，比如视频列表啥的。

提供一个思路供参考：
1. 创建自己的templates页面，例如：`video_change_list.html`；
2. `video_change_list.html`继承`admin/change_list.html`并添加自己的逻辑，可参考[link](https://github.com/wuyue92tree/django-adminlte-ui/blob/master/adminlteui/templates/adminlte/menu_change_list.html)
3. 修改对应的view指向`video_change_list.html`(如果是Admin页面，可通过`change_list_template`进行设置[link](https://github.com/wuyue92tree/django-adminlte-ui/blob/master/adminlteui/admin.py))
```

class MenuAdmin(TreeAdmin):
--
  | list_display = ('name', 'position', 'link_type', 'display_link',
  | 'display_content_type', 'priority_level', 'display_icon',
  | 'valid')
  | list_filter = ('position', 'link_type', 'valid')
  | list_editable = ('valid', 'priority_level')
  | form = movenodeform_factory(Menu)
  | change_list_template = 'adminlte/menu_change_list.html'
  | change_form_template = 'adminlte/menu_change_form.html'

```

**Comment by KissWorld** [comment]
增加了一个自定义权限之后报错   
![WX20200821-110406](https://user-images.githubusercontent.com/3635669/90847894-25fe9280-e39e-11ea-8bd9-1b3b18e721aa.png)

**Comment by KissWorld** [comment]
这问题算是解决了，另外的问题，在帮忙看看吧
