### ISSUE TITLE
富文本解析

### ISSUE THREAD

**Issue by KissWorld** [wuyue92tree/django-adminlte-ui#24]
![WX20200824-002251](https://user-images.githubusercontent.com/3635669/90983623-21a2c700-e5a2-11ea-9cd7-c0e63e6e2782.png)

通用表单能否加入富文本解析显示呀

**Comment by wuyue92tree** [comment]
富文本可参考如下两个库
https://github.com/django-ckeditor/django-ckeditor
https://github.com/pylixm/django-mdeditor （markdown）

**Comment by KissWorld** [comment]
这个没问题，有问题的是显示，怎么搞都不显示，都是转义的。
