### ISSUE TITLE
自定义菜单排序问题

### ISSUE THREAD

**Issue by justong86** [wuyue92tree/django-adminlte-ui#3]
您好：
     现在默认的自定义菜单会自动按名称排序，如果让我手工来固定住显示顺序呢？

**Comment by wuyue92tree** [comment]
> 您好：
> 现在默认的自定义菜单会自动按名称排序，如果让我手工来固定住显示顺序呢？

在菜单表中新增一个优先级字段，渲染菜单的时候先通过优先级进行排序，这个我研究下，在下一个版本中加上。
