### ISSUE TITLE
'treebeard_css', expected 'endblock'. Did you forget to register or load this tag?

### ISSUE THREAD

**Issue by shusqn** [wuyue92tree/django-adminlte-ui#30]
<html>
<body>
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">TemplateSyntaxError at /admin/django_admin_settings/menu/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; word-break: break-word; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Invalid block tag on line 7: 'treebeard_css', expected 'endblock'. Did you forget to register or load this tag?</pre>

Request Method: | GET
-- | --
http://127.0.0.1:8000/admin/django_admin_settings/menu/
4.2.1
TemplateSyntaxError
Invalid block tag on line 7: 'treebeard_css', expected 'endblock'. Did you forget to register or load this tag?
C:\Users\fanyou\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py, line 558, in invalid_block_tag
treebeard.admin.changelist_view
C:\Users\fanyou\AppData\Local\Programs\Python\Python311\python.exe
3.11.3
['C:\\sanjie\\git\\sanjie-python\\sanjie_admin_dj',  'c:\\Users\\fanyou\\.vscode\\extensions\\ms-python.python-2022.20.2\\pythonFiles\\lib\\python\\debugpy\\_vendored\\pydevd',  'C:\\Users\\fanyou\\AppData\\Local\\Programs\\Python\\Python311\\python311.zip',  'C:\\Users\\fanyou\\AppData\\Local\\Programs\\Python\\Python311\\DLLs',  'C:\\Users\\fanyou\\AppData\\Local\\Programs\\Python\\Python311\\Lib',  'C:\\Users\\fanyou\\AppData\\Local\\Programs\\Python\\Python311',  'C:\\Users\\fanyou\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages',  'C:\\Users\\fanyou\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\win32',  'C:\\Users\\fanyou\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\win32\\lib',  'C:\\Users\\fanyou\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\Pythonwin']

</body>
</html>

**Comment by youyoubilly** [comment]
I got this bug as well. please help~ thanks!

**Comment by wuyue92tree** [comment]
Try new version please 2.0.0
