### ISSUE TITLE
 关于升级到adminLTE 2.4.X的问题

### ISSUE THREAD

**Issue by justong86** [wuyue92tree/django-adminlte-ui#5]
由于要使用jQuery 3.0以上版本，本项目集成的jQuery是2.2版本。所以尝试升级到adminlte2.4，按照官方升级指导https://adminlte.io/docs/2.4/upgrade-guide   ，使用adminlte.min.js替代了app.min.js。随后出现了问题，表现为左侧导航栏会一闪而逝。由于前端js水平有限，没有找到解决方法。
如果能升级一下adminlte版本就更完美了，谢谢。

**Comment by wuyue92tree** [comment]
> 由于要使用jQuery 3.0以上版本，本项目集成的jQuery是2.2版本。所以尝试升级到adminlte2.4，按照官方升级指导https://adminlte.io/docs/2.4/upgrade-guide ，使用adminlte.min.js替代了app.min.js。随后出现了问题，表现为左侧导航栏会一闪而逝。由于前端js水平有限，没有找到解决方法。
> 如果能升级一下adminlte版本就更完美了，谢谢。

你可以先通过覆盖 admin/base.html的方式引入jQuery3.0，当前暂不考虑升级adminLTE版本

**Comment by wuyue92tree** [comment]
已更新至 2.4.18
